version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aprovei_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_forte_filda
      POSTGRES_DB: aprovei
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aprovei_backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:senha_forte_filda@db:5432/aprovei
      - SECRET_KEY=uma_chave_super_segura_e_longa_para_filda_2026
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - backend_storage:/app/storage
      - /home/genial/Lunar:/app/lunar_local:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aprovei_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  backend_storage:
